name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: Flixe Project
          column: In Progress
          repo-token: ${{ secrets.ACTION_TOKEN }}


