name: List Projects
on:
  issues:
    types: [assigned]
jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: List projects
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const projects = await github.rest.projects.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              if (projects.data.length === 0) {
                console.log(await github.rest.projects.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
              }););
              } else {
                console.log(projects.data.map(project => project.name));
              }
            } catch (error) {
              console.error('Error fetching projects:', error);
            }
